README.md
interceptor.go

Returning a rtp.Packet requires an extra allocation.
Resolves #14

Update RTP/RTCP Read to be []byte

---

README.md
pkg/nack/generator_interceptor_test.go

Nothing particular, but the expected value is the 2nd argument, and the actual value the 3rd (i was copying and pasting code for my report patch and i realized that i was using the wrong syntax)

fix arguments of assert.Equal in NACK tests

---

pkg/nack/generator_interceptor.go
pkg/nack/responder_interceptor.go

sync.Map is never copied, therefore a pointer is not necessary.

Save sync.Map by value, not by reference

---

internal/test/mock_time.go
pkg/report/receiver_interceptor.go
pkg/report/receiver_interceptor_test.go
pkg/report/receiver_option.go
pkg/report/receiver_stream.go
pkg/report/report.go
pkg/report/sender_interceptor.go
pkg/report/sender_interceptor_test.go
pkg/report/sender_option.go
pkg/report/sender_stream.go

This PR implements sender and receiver reports, without bandwidth estimation.
Missing features:
* <s>Reordered RTP packets are not counted correctly - RTP packets should be saved in a map (like the NACK interceptor does) and processed afterwards</s>

Implement Sender and Receiver reports

---

pkg/mock/interceptor.go
pkg/mock/interceptor_test.go

Call registered functions when interceptor methods are called.
Used by https://github.com/pion/webrtc/pull/1721

Add mock Interceptor for testing

---

README.md
pkg/twcc/header_extension.go
pkg/twcc/header_extension_test.go
pkg/twcc/sender_interceptor.go
pkg/twcc/sender_interceptor_test.go
pkg/twcc/twcc.go
pkg/twcc/twcc_test.go

https://datatracker.ietf.org/doc/html/draft-holmer-rmcat-transport-wide-cc-extensions-01

Implement Transport Wide Congestion Control

---

pkg/twcc/header_extension.go
pkg/twcc/sender_interceptor.go
pkg/twcc/sender_interceptor_test.go
pkg/twcc/twcc.go
pkg/twcc/twcc_test.go

`seqNr` isn't one I commonly see. `arrivalTime` just to match the RFC a bit more. 
Feel free to push back @mengelbart if you disagree! I am just confirming that everything works before merging pion/webrtc

Lengthen some acronyms

---

pkg/twcc/sender_interceptor.go
pkg/twcc/twcc.go
pkg/twcc/twcc_test.go

We would expect Milliseconds, but then convert to Microseconds
internally.

Use microseconds for TWCC API

---

pkg/twcc/twcc.go
pkg/twcc/twcc_test.go

pion/rtcp expects input to be in Nanoseconds, and does n / 250 during
the marshal.
Resolves #61

Use proper units with rtcp TWCC packets

---

examples/nack/main.go
interceptor.go
pkg/mock/factory.go
pkg/nack/generator_interceptor.go
pkg/nack/generator_interceptor_test.go
pkg/nack/responder_interceptor.go
pkg/nack/responder_interceptor_test.go
pkg/report/receiver_interceptor.go
pkg/report/receiver_interceptor_test.go
pkg/report/sender_interceptor.go
pkg/report/sender_interceptor_test.go
pkg/twcc/header_extension_interceptor.go
pkg/twcc/header_extension_interceptor_test.go
pkg/twcc/sender_interceptor.go
pkg/twcc/sender_interceptor_test.go
registry.go

Interceptors are being accidentally misused by users.
The issue is that an Interceptor can be re-used between
multiple PeerConnections. Interceptors were designed to only be
single PeerConnection aware, so state is being corrupted.
Instead we are now going to provide InterceptorFactories. The default
API of pion/webrtc will now be safe to use between PeerConnections.
Relates to pion/webrtc#1956

Add InterceptorFactory

---

attributes.go
attributes_test.go
pkg/nack/generator_interceptor.go
pkg/nack/responder_interceptor.go
pkg/report/receiver_interceptor.go
pkg/report/receiver_stream.go
pkg/twcc/sender_interceptor.go

RTCP headers are never used alone, interceptors always need to parse a
slice of RTCP packets.

Store RTCP packet slice instead of headers

---

AUTHORS.txt
README.md
pkg/packetdump/filter.go
pkg/packetdump/format.go
pkg/packetdump/option.go
pkg/packetdump/packet_dump.go
pkg/packetdump/packet_dumper.go
pkg/packetdump/receiver_interceptor.go
pkg/packetdump/receiver_interceptor_test.go
pkg/packetdump/sender_interceptor.go
pkg/packetdump/sender_interceptor_test.go

This PR adds interceptors capable of dumping RTP & RTCP packets.
The interceptors directly write to a `io.Writer` which defaults to `os.Stdout` and can be configured by the user.
The RTP and RTCP packets can be dumped based on a filter provided by the user. By default, every packet is dumped.
Hopefully, this is what you had in mind @Sean-Der when writing the [2021 Goals](https://github.com/pion/webrtc/wiki/Goals-2021) 😁

Packet Dumper Interceptors

---

AUTHORS.txt
pkg/nack/generator_interceptor.go
pkg/nack/receive_log_test.go
pkg/nack/responder_interceptor.go
pkg/packetdump/receiver_interceptor.go
pkg/report/receiver_interceptor.go
pkg/twcc/header_extension_interceptor.go
pkg/twcc/sender_interceptor.go

We started using attributes to store headers instead of repeatedly
parsing them in every interceptor. This only works if the attributes are
initialized before they are used.

Fix assignment to entry in nil map

---

examples/nack/main.go

Changing `rtcpWriter` to `rtcpReader` to match the actual behavio

Fixing confusing variable name

---

pkg/twcc/twcc.go
pkg/twcc/twcc_test.go

Always encode all of the remaining deltas in the last chunk. This did
not happen, when the chunk contained more than 7 but less than 14
deltas. This can happen, if we added 8 symbols that fit in one symbol,
but then had to start a new chunk, because the next symbol was too big.
Also happens, if we're done after more than 7, but less than 14 symbols.
In this case, it might be possible to optimize for space and only use
one symbol, but in most cases this will not make a difference and we
would have to check if the chunk only contains symbols that can be
represented by 1 bit.

Fix a bug in Chunk encoding

---

AUTHORS.txt
pkg/nack/errors.go
pkg/nack/responder_interceptor.go
pkg/nack/retainable_packet.go
pkg/nack/send_buffer.go
pkg/nack/send_buffer_test.go

Keeps a copy of packet in responder_interceptor, fixes #84
While trying to fix this, I was also thinking about how we might reduce copy/allocations throughout pion. Have implemented a version of this that works within intercepters (unexported for now). any feedback is welcome!

Fix NACK interceptor sendBuffer overridden

---

internal/cc/feedback_adapter.go

Previously when the TWCC header extension was present but the
sequence numbers weren't added, the error message reported was
`failed to write packet: buffer too small`. This was difficult
to debug, so now the error message properly reports that the
TWCC header value was not set.

Update TWCC error message

---

AUTHORS.txt
internal/cc/feedback_adapter.go
internal/cc/feedback_adapter_test.go
pkg/gcc/send_side_bwe.go

This ignores RTCP packets the we can't handle instead of returning
errors. The feedback might still be useful for other interceptors.

Ignore unrelated RTCP in FeedbackAdapter

---

pkg/gcc/gcc.go
pkg/gcc/gcc_test.go

This PR fixes a bug in `clampInt` and tests `clampInt` and `clampDuration`. Without this fix, `clampInt(a, a, b)` results in `b`, but it should be `a`. `clampDuration` was correct before, but now uses the same logic as `clampInt` and both are tested.

Fix and test clamping functions

---

pkg/report/sender_interceptor.go
pkg/report/sender_stream.go

In this way, receiver and sender report generators are aligned

Move sender report generation into sender_stream.go

---

pkg/twcc/sender_interceptor.go
pkg/twcc/sender_interceptor_test.go

TWCC currently starts sending empty reports as soon as an RTCP writer is
setup. This leads to errors before the connection is setup properly.
This change makes the interceptor wait until the first packet arrived
before sending any reports.

Make TWCC wait until first packet before reporting

---

pkg/packetdump/packet_dumper.go

Fixes a deadlock that occurs when trying to write to a closed packetdumper.

Ignore write when closed

---

pkg/gcc/send_side_bwe.go
pkg/gcc/send_side_bwe_test.go

Return an error when `WriteRTCP` is called after the `SendSideBWE` is closed
Fixes #131

fix(ss-bwe): `WriteRTCP` raise panic after `Close`

---

pkg/gcc/arrival_group_accumulator.go
pkg/gcc/arrival_group_accumulator_test.go
pkg/gcc/delay_based_bwe.go
pkg/gcc/overuse_detector.go
pkg/gcc/overuse_detector_test.go
pkg/gcc/rate_calculator.go
pkg/gcc/rate_calculator_test.go
pkg/gcc/rate_controller.go
pkg/gcc/rate_controller_test.go
pkg/gcc/rtt_estimator.go
pkg/gcc/rtt_estimator_test.go
pkg/gcc/slope_estimator.go
pkg/gcc/slope_estimator_test.go

Reduces the number of goroutines that are spawned for a process that always runs sequentially anyway. Additionally, cleans up and moves some code to more appropriate files.

Clean up delay based bwe and use less goroutines

---

pkg/stats/stats_recorder.go
pkg/stats/stats_recorder_test.go

`time.Duration(xrReport.DLRR/65536.0)`  
This will cause precision lost. for example, when xrReport.DLRR=30000, result 0 is unexpected. 
Following the method just like dlsr
`dlsr := time.Duration(float64(report.Delay) / 65536.0 * float64(time.Second))`

BugFix: When calculating dlrr, precision is lost in integer operations, errors occur in rtt calculations.

---

pkg/nack/generator_interceptor.go

The interceptor embeds the NoOp interceptor, so this is not a breaking change. UnbindLocalStream will no longer remove any state. Only when UnbindRemoteStream is called will the state be removed.
Fixes #154

Unbinding should happen on remote stream

---

pkg/gcc/adaptive_threshold.go

Fig bug: in adaptive_threshold.go, the add,time.Duration() will round add, and adjustment of the threshold will always be zeros.
we print information as follows
`fmt.Printf("thresh: %f,%s,%s\n",add,time.Duration(add)*1000* time.Microsecond,time.Duration(add*1000)* time.Microsecond)`

Fix a bug in adaptive_threshold

---

pkg/gcc/adaptive_threshold.go
pkg/stats/stats_recorder.go
pkg/stats/stats_recorder_test.go

When closing a `PeerConnection` that is using the stats recorder as an interceptor, the process may block. I've dug a little bit and found out the calls to `GetStats()`, `QueueIncomingRTP()`, `QueueIncomingRTCP()`, `QueueOutgoingRTP()` and `QueueOutgoingRTCP()` block when the recorder is not yet started or stopped. I've added both `TestGetStatsNotBlocking` and `TestQueueNotBlocking` tests to test this.
I've proposed a fix which consists of replacing channels with mutexes but an alternative would be to wrap channel calls around a mutex.
Let me know what you think.
Cheers

Fix stats recorder actions that block when not yet started or stopped

---

AUTHORS.txt
pkg/twcc/twcc.go
pkg/twcc/twcc_test.go

Instead return nil to the caller and don't modify any internal state
Resolves #159

Don't discarding if TWCC Generator isn't ready

---

AUTHORS.txt
pkg/stats/stats_recorder.go
pkg/stats/stats_recorder_test.go

Otherwise, we would record packets and reports which do not belong to the stream that is monitored by this recorder.
Fixes #166 #168

Filter packets and reports by SSRC

---

AUTHORS.txt
pkg/twcc/header_extension_interceptor.go
pkg/twcc/header_extension_interceptor_test.go

Fixes https://github.com/pion/interceptor/issues/185
I was not sure about if it should fail silently, ignoring setting header and continue or returning error. I opted for the second, so that it is transparent that something is not right when header is nil.

Fix set extension on nil header

---

pkg/report/sender_interceptor.go
pkg/report/sender_interceptor_test.go
pkg/report/sender_option.go
pkg/report/ticker.go

This lets consumers use the Sender Report interceptor in tests that utilize fake clocks. Previously the current time could be injected, but the interceptor would only run according to real-time based on `time.NewTicker`, but now tests can control when the reports are generated.

Enable injecting ticker to Sender Report interceptor

---

AUTHORS.txt
pkg/twcc/twcc.go
pkg/twcc/twcc_test.go

When using `twcc.Recorder` outside the context of `twcc.SenderInterceptor`, it is useful to have access to the number of packets currently held. This enables writing logic other than an interval to determine when to build feedback packets.
N/A

Add PacketsHeld to TWCC recorder

---

pkg/twcc/twcc.go
pkg/twcc/twcc_test.go

Prior to this change, a sequence of small receive deltas could get erroneously encoded as a series of 0s.
If the actual receive deltas were {200μs, 200μs, ..., 200μs}, what was appearing in the TWCC feedback packet (after marshaling) was {0, 0, ..., 0}. (Note: the added test, without the code fixes, would fail by returning deltas of {200, 200, ..., 200}, but marshalling the feedback packet would truncate all of those to 0).
To fix this, receive deltas are rounded to the closest "delta tick" period (250μs) as opposed to truncating. Additionally, `lastTimestampUS` is moved forward by the rounded delta instead of set to the timestamp of the last packet. This lets rounding errors accumulate so that a series of packets will have the correct sum of receive deltas (within the margin of error of …

TWCC: Fix small receive delta rounding

---

pkg/twcc/arrival_time_map.go
pkg/twcc/arrival_time_map_test.go
pkg/twcc/sender_interceptor.go
pkg/twcc/twcc.go
pkg/twcc/twcc_test.go

The previous implementation of the TWCC sender interceptor had some inconsistencies with libwebrtc. Namely, if there were missing packets between the last packet in the previous feedback interval and the first received packet in the following feedback interval, then those packets were never included as missing in any feedback.
This is an issue because libwebrtc uses data about lost packets from TWCC feedback in their congestion controller. This means that bursts of loss could go unnoticed by libwebrtc, causing the application to possibly send more data than it would if the loss was properly reported.
Another minor difference was that feedback packets with a single packet are in fact valid according to the RFC, but we were only returning feedback with at least two packets. libwebrtc has a …

Partial rewrite of TWCC sender

---

pkg/report/sender_interceptor.go
pkg/report/sender_interceptor_test.go
pkg/report/sender_option.go
pkg/report/sender_stream.go

If a sender report is generated immediately after sending an out-of-order packet (which can happen e.g. in an SFU when forwarding media), the timestamp from the last in-order packet should be extrapolated, since the departure time of an out-of-order packet is is not properly correlated with its RTP timestamp.
Leave an option to re-enable the old behavior.

Don't use out-of-order packets to calculate RTPTime for sender reports

---

pkg/nack/generator_interceptor.go
pkg/nack/generator_option.go

Currently the NACK generator interceptor has no limit on the number of NACKs produced for the same lost packet. If the remote takes a while to resend the packet (e.g. if the RTT is larger than the NACK generator interval), this can result in the remote resending a NACKed packet an unlimited number of times (or at least until sufficient later packets are received that the NACK receive log wraps around). If there's congestion on the link, this will make the congestion even worse. Also, after a certain amount of time, receiving a lost packet is no longer useful (e.g. beyond the length of the jitter buffer on the receive side).
This PR adds a new generator option to limit the maximum number of times a given lost packet is NACKed. So for example, if this option is set to 4, a lost packet is …

Option to limit max NACKs per lost packet

---

AUTHORS.txt
pkg/report/receiver_interceptor_test.go
pkg/report/receiver_stream.go

Sequence number cycle calculation was over estimating the cycles if packets came out of order. A sequence like 65535, 0, 65534 would increment the cycle counter twice.

Fix wrap around on out of order packet

---

pkg/nack/generator_interceptor.go

Following PR #208, the NACK generator interceptor may send NACK RTCP packets even if there are no missing packets to NACK (specifically if the receive log indicates missing packets, but we've already hit the NACK send limit for those so do not need to NACK those any further). This is functionally 'harmless' but wastes link bandwidth. This PR skips sending a NACK RTCP packet if there are no packets to NACK.

Do not send empty NACK packets

---

AUTHORS.txt
pkg/flexfec/flexfec_coverage.go
pkg/flexfec/flexfec_encoder.go
pkg/flexfec/util/bitarray.go
pkg/flexfec/util/media_packet_iterator.go

- Context:
FlexFec is a packet loss recovery technique through which redundant RTP packets are sent and from which missing RTP packets can potentially be reconstructed.
https://datatracker.ietf.org/doc/html/rfc8627
- Summary:
There are multiple variants of FlexFec and I'm adding an implementation of the "Flex" encoder as part of this PR.
The other variants are not included nor is the decoder included which I hope to add in subsequent PRs, this first one is meant to be the start of a series.
This PR also doesn't add the interceptor on top of the encoder.
I'm labeling it as DRAFT for now until I write some proper unit tests to get us some confidence that it works as expected.
Fixes #...

[FlexFec] Adding FlexFec Flex variant encoder implementation

---

pkg/report/sender_stream.go

A sequence like
66533 -> 0 -> 65534
would have been detected as in-order as 65534 - 0 > 0.

Fix out of order check

---

pkg/flexfec/encoder_interceptor.go
pkg/flexfec/flexfec_coverage.go
pkg/flexfec/flexfec_encoder_03.go
pkg/flexfec/util/bitarray.go

This PR is part of a series of PRs to provide FlexFec support for pion.
https://datatracker.ietf.org/doc/html/rfc8627
This PR provides the following:
- Adding a FlexFec encoder implementation for https://datatracker.ietf.org/doc/html/draft-ietf-payload-flexible-fec-scheme-03 => This is the implementation that chromium currently uses instead of the latest version of the draft. Providing support for this draft version will enable pion to work with chromium-based browsers.
- Changing the FEC coverage data structure to use 2 uint64 to store the packet masks. This will reduce allocations.
- Adding support for the actual Interceptor component that batches RTP packets together to generate repair packets before sending both types of packets over the network.
- Various fixes to FEC header …

[FlexFec] Adding support for FlexFec RFC-03

---

pkg/jitterbuffer/jitter_buffer.go
pkg/jitterbuffer/jitter_buffer_test.go
pkg/jitterbuffer/priority_queue.go
pkg/jitterbuffer/priority_queue_test.go

This PR adds a very simple jitter buffer for RTP packets. The goal of this is to slowly introduce jitter buffers in places which network jitter can critically impact stream performance without causing unnecessary delay. Right now the heuristic is set at a fixed packet count before moving to the playback state, but this algorithm will be adjusted (and additional dynamic algorithms introduced) in future work.
This jitter buffer relies on a priority queue based on the RTP packet's sequence number. It will insert new packets in priority of sequence number, tracks when its current simplistic total packet count is met to emit a playback event and allows Pop-ing packets off either from the play head (defined as the head position when the jitter buffer met its minimum length) or at a specific …

Add an initial, very simple, jitter buffer

---

pkg/report/receiver_interceptor.go
pkg/report/sender_interceptor.go
pkg/rfc8888/recorder_test.go

UnbindLocalStream for Sender
UnbindRemoteStream for Receiver

Unbind stream for report interceptor

---

pkg/jitterbuffer/jitter_buffer.go
pkg/jitterbuffer/jitter_buffer_test.go

For the tests (and probably generally to start)  we need a way to set when the jitter buffer will begin emitting packets, having met it's minimum threshold.

JitterBuffer Enhancements: Allow setting a minimum length

---

pkg/jitterbuffer/jitter_buffer.go
pkg/jitterbuffer/jitter_buffer_test.go

Allow the user to Get+Set PlayoutHead of the JitterBuffer

Add SetPlayoutHead

---

pkg/jitterbuffer/jitter_buffer_test.go
pkg/jitterbuffer/priority_queue.go
pkg/jitterbuffer/priority_queue_test.go

This fixes a few issues with the priority queue not decrementing its count and adds some more test coverage.
Fixes #248

JitterBuffer: Fix queue not properly decrementing packet count in some instances

---

attributes.go
internal/test/mock_stream.go
pkg/jitterbuffer/jitter_buffer.go
pkg/jitterbuffer/jitter_buffer_test.go
pkg/jitterbuffer/option.go
pkg/jitterbuffer/priority_queue.go
pkg/jitterbuffer/priority_queue_test.go
pkg/jitterbuffer/receiver_interceptor.go
pkg/jitterbuffer/receiver_interceptor_test.go

This implements a RemoteStream jitter buffer interceptor.

JitterBuffer: Interceptor

---

pkg/nack/generator_interceptor.go
pkg/nack/generator_interceptor_test.go
pkg/nack/generator_option.go
pkg/nack/responder_interceptor.go
pkg/nack/responder_interceptor_test.go
pkg/nack/responder_option.go

This change allows users to pass custom stream filters to the nack interceptor in order to enable/disable nacks for certain streams based on the StreamInfo.

Support custom streams filter in nack interceptor

---

pkg/nack/responder_interceptor.go
pkg/nack/responder_interceptor_test.go

Support TrackLocal RTX

---

pkg/nack/responder_interceptor.go
pkg/nack/retainable_packet.go
pkg/nack/send_buffer.go
pkg/nack/send_buffer_test.go

Modify packets before adding them to NACK buffer.
WARNING: DATA RACE
Read at 0x00c00056d456 by goroutine 10741:
github.com/pion/interceptor/pkg/nack.(*sendBuffer).get()
/home/runner/go/pkg/mod/github.com/pion/interceptor@v0.1.35/pkg/nack/send_buffer.go:95 +0x1e4
github.com/pion/interceptor/pkg/nack.(*ResponderInterceptor).resendPackets.func1()
/home/runner/go/pkg/mod/github.com/pion/interceptor@v0.1.35/pkg/nack/responder_interceptor.go:153 +0x70
github.com/pion/rtcp.(*NackPair).Range()
/home/runner/go/pkg/mod/github.com/pion/rtcp@v1.2.14/transport_layer_nack.go:65 +0x43
github.com/pion/interceptor/pkg/nack.(*ResponderInterceptor).resendPackets()
/home/runner/go/pkg/mod/github.com/pion/interceptor@v0.1.35/pkg/nack/responder_interceptor.go:152 +0x124 …

Fix race in a03526d8eb82

---

pkg/nack/retainable_packet.go

I got runtime panic from [this line](https://github.com/pion/interceptor/blob/bfda3e00334428a1192adb1773f2c408799713f5/pkg/nack/retainable_packet.go#L82) when calculating the padding size but the payload size is zero.  
My code is a simple WHIP WHEP but using NACK through `webrtc.NewPeerConnection()`. This is happen when a browser publish a stream to WHIP endpoint and another browser trying to subscribe using WHEP.
```
Exception has occurred: panic
"runtime error: index out of range [-1]"
Stack:
3  0x0000000102a8d4d8 in github.com/pion/interceptor/pkg/nack.(*packetManager).NewPacket
at /Users/tyohan/go/pkg/mod/github.com/pion/interceptor@v0.1.36/pkg/nack/retainable_packet.go:82
4  0x0000000102a8c4b8 in github.com/pion/interceptor/pkg/nack.(*ResponderInterceptor).BindLocalStream.func1
at …
```

Fix payload size zero cause runtime panic on calculating padding size

---

internal/rtpbuffer/packet_factory.go
internal/rtpbuffer/rtpbuffer_test.go

Fix Excessive GC Pressure due, 
https://github.com/pion/interceptor/blob/d34a3c57ed805341d5902ec5fc2838794aa713fc/internal/rtpbuffer/packet_factory.go#L94
https://github.com/pion/interceptor/blob/d34a3c57ed805341d5902ec5fc2838794aa713fc/internal/rtpbuffer/packet_factory.go#L96
Fixes #281

Fix: Excessive GC CPU pressure caused by unwanted heap memory #281

---

pkg/gcc/kalman.go

Fixes a deviation from the GCC rfc spec.
Fixes #286

gcc: fix missing if-else in kalman

---

internal/cc/acknowledgment.go

Fixed a typo which I noticed while reading the code.

Fixed typo in string method

---

internal/rtpbuffer/rtpbuffer.go
internal/rtpbuffer/rtpbuffer_test.go

There was previously an issue with the nack buffer that would occur when an uploader was experiencing packet loss (or otherwise had reordering occur). `lastAdded` was getting set for every packet added to the buffer, but packets could get added out of order, causing `lastAdded` to go backwards. The impact was that packets at the end of the buffer were sometimes considered stale and cleared out. Consider the following sequence of packets being added to the buffer:
1, 2, 4, 3, 5, ...
When 4 is added, `lastAdded` would correctly be 4, but then when 3 arrived, `lastAdded` would go backwards to 3. This would cause two related problems: trying to get 4 from the buffer would fail (`uint16(3 - 4) > Uint16SizeHalf`), and then when we add 5, we would treat 4 as a gap between `lastAdded` (3) and …

Fix nack buffer RTX issue

---

pkg/gcc/arrival_group.go
pkg/gcc/arrival_group_accumulator.go
pkg/gcc/arrival_group_accumulator_test.go
pkg/gcc/arrival_group_test.go

See referenced issue for background
Fixes #274

Fixes bug in group accumulator

---

pkg/packetdump/filter.go
pkg/packetdump/format.go
pkg/packetdump/option.go
pkg/packetdump/packet_dumper.go
pkg/packetdump/receiver_interceptor_test.go
pkg/packetdump/sender_interceptor_test.go

This PR adds new packet dumper options that let you use RTP/RTCP formatters returning `[]byte` instead of strings. This makes it easier to create dumpers that save RTP data in binary formats like PCAP. The formatter and filter APIs are also updated to handle one RTCP packet at a time, making them consistent with how RTP is handled.

Binary formatters in packetdump

---

internal/ntp/ntp.go
internal/ntp/ntp_test.go
pkg/rfc8888/recorder.go
pkg/rfc8888/recorder_test.go

Moves all NTP-related functions to the NTP package and adds a function to recover a time.Time from a uint32 encoded NTP timestamp. This allows reusing code for CCFB handling (and testing).

Move NTP function to ntp package and add ToTime32

---

pkg/nack/responder_interceptor.go
pkg/nack/responder_interceptor_test.go

The current implementation of RTX in the NACK interceptor implies that there may be packets with different SSRCs in a single RTP stream (stream in terms of the interceptor interface), e.g., with `SSRCRetransmission` or (more importantly for this PR) `SSRCForwardErrorCorrection`. These packets should not be stored in the buffer or used for responding to NACKs.
I suggest skipping such packets in the responder interceptor. This might be a breaking change for some exotic use cases, but I can't think of any sensible scenario where the NACK interceptor is used to resend packets with a non-main SSRC. Therefore, I believe this is a reasonable default.

NACK responder: bypass auxiliary SSRCs

---

pkg/nack/responder_interceptor.go
pkg/nack/responder_interceptor_test.go

Fixes the following panic:
```
fatal error: concurrent map read and map write 
github.com/pion/interceptor/pkg/nack.(*ResponderInterceptor).BindLocalStream.func1(0xc0b16fae10, {0xc03af93210, 0x467, 0x467}, 0xc0a8afe9c0)
github.com/pion/interceptor/pkg/nack/responder_interceptor.go:126 +0x145 github.com/pion/interceptor.RTPWriterFunc.Write
```
Looks like race was introduced in d34a3c5

Fix race in nack responder 

---

pkg/rfc8888/interceptor.go

This is not really a bug but annoying to receivers of our reports. If the ticker ticks, but then another packet is handled first, the timestamp of the report (from the ticker) will be before the receive timestamp of the last packet in the report. In that case, the report contains a 0x1FFF value to indicate that the packet was received after the report. However, we know the timestamp and can send it, if we take the timstamp after entering the case branch. At that time, it is guaranteed, that no additional packets can be added to the report.

Fix report timestamps

---

.golangci.yml
errors_test.go
internal/rtpbuffer/rtpbuffer_test.go
internal/test/mock_stream_test.go
pkg/gcc/send_side_bwe_test.go
pkg/mock/interceptor_test.go
pkg/nack/generator_interceptor_test.go
pkg/nack/receive_log_test.go
pkg/nack/responder_interceptor_test.go
pkg/rfc8888/interceptor_test.go
pkg/stats/stats_recorder_test.go
pkg/twcc/header_extension_interceptor_test.go
pkg/twcc/twcc_test.go

Description
Use testify's assert package instead of the standard library's testing package.
Reference issue
https://github.com/pion/.goassets/pull/222

Update lint rules, force testify/assert for tests

---

pkg/nack/generator_interceptor.go
pkg/nack/generator_interceptor_test.go
pkg/nack/receive_log.go
pkg/nack/receive_log_test.go

Refactored packet processing to avoid multiple make calls and eliminate the use of append. This reduces garbage collection overhead and improves overall memory management efficiency.
Fixes #...

Improve memory efficiency

---

README.md
pkg/flexfec/encoder_interceptor.go
pkg/flexfec/encoder_interceptor_test.go
pkg/flexfec/flexfec_03_test.go
pkg/flexfec/flexfec_encoder.go
pkg/flexfec/flexfec_encoder_03.go
pkg/flexfec/flexfec_encoder_03_test.go
pkg/flexfec/option.go

1. Pass in correct payload type and ssrc (don't use the video track's payload type and ssrc
2. Store only main ssrc packets in buffer
3. Allow custom FEC encoders
4. Add options for NumMediaPackets and NumFECPackets
5. Allow multiple RTP streams with FEC support
6. Encode FEC only if negotiated 
Fixes https://github.com/pion/interceptor/issues/332

FEC interceptor enhancements

---

internal/rtpbuffer/errors.go
internal/rtpbuffer/packet_factory.go
internal/rtpbuffer/rtpbuffer_test.go

RTP padding overflow is now handled, instead of catching a panic. https://github.com/pion/webrtc/issues/3148
Fixes https://github.com/pion/webrtc/issues/3148

Fix padding overflow with PacketFactory

---

internal/rtpbuffer/packet_factory.go
internal/rtpbuffer/rtpbuffer_test.go

PacketFactoryCopy.NewPacket does not handle case when padding size is set in Header.PaddingSize and no padding is in payload. It would try to remove it and either it would create broken packet or return error. It should not do this when PaddingSize field is set.
This is another part of fix for https://github.com/pion/webrtc/issues/2403

Handle Header.PaddingSize in PacketFactoryCopy

---

pkg/packetdump/default_packet_logger.go
pkg/packetdump/option.go
pkg/packetdump/packet_dumper.go
pkg/packetdump/packet_dumper_test.go
pkg/packetdump/packet_logger.go

The current implementation allows users to specify custom writers and custom formatters. But now Go has built-in structured logging, so I would like to do something like this:
```
slog.Info("received RTP packet", "sequence-number", pkt.header.SequenceNumber)
```
I think this is not possible with the current implementation. This PR allows me to provide a custom logger that can then implement any form of custom logging.

Allow users to provide a custom logger implementation

---

registry.go

Optimize memory allocation by preallocating interceptors slice with known capacity to avoid multiple reallocations during append operations.

Preallocate slice capacity in Registry.Build()

---

pkg/twcc/arrival_time_map.go

Remove unused named return parameters from `FindNextAtOrAfter` method as they were not being used in the function implementation.

Remove unused named return parameters

---

pkg/stats/stats_recorder.go
pkg/stats/stats_recorder_test.go

The previous jitter calculation was not following RFC3550 and reported incorrect values, as can be seen in the first modified test which reports a high jitter despite all packets arriving perfectly spaced (in both RTP timestamp and Pion receival timestamp).
Additionally, other implementations report the jitter in seconds instead of RTP timestamp units which are dependent on the streams clock rate, which should now also be the case here.
Fixes #234

Fix jitter calculation to match RFC3550 and convert to seconds

---

pkg/flexfec/flexfec_decoder_03.go
pkg/gcc/adaptive_threshold.go
pkg/gcc/gcc.go
pkg/gcc/gcc_test.go
pkg/gcc/loss_based_bwe.go
pkg/gcc/send_side_bwe.go
pkg/stats/stats_recorder.go
pkg/twcc/arrival_time_map.go
pkg/twcc/twcc.go

This pull request proposes an update to the Go version, elevating it from 1.20 to 1.21.
This change is dependent on https://github.com/pion/.goassets/pull/233

Use Go 1.21 built-in min function

---

pkg/report/sender_stream.go

With large samples like key frame, they could be hundreds of packets. Updating the last packet time on each of those packets means the sender report could be off by the amount of time it takes to send the full sample which could be a few ms.

Update last packet time only on change
